In [1]:
import numpy as np

## Numpy 문제

### 📝 문제 1: 기본 벡터 만들기 (난이도: ⭐)

In [3]:
# 문제 1 답안을 여기에 작성하세요!

# 1-1) 행 벡터 만들기
my_row_vector = np.array([10,20,30])

# 1-2) 열 벡터 만들기  
my_col_vector = np.array([[5], [15], [25]])

# 결과 확인
print("행 벡터:")
display(my_row_vector)
print("열 벡터:")
display(my_col_vector)

행 벡터:


array([10, 20, 30])

열 벡터:


array([[ 5],
       [15],
       [25]])

### 📝 문제 2: 행렬 만들기 (난이도: ⭐⭐)

In [4]:
# 문제 2 답안을 여기에 작성하세요!

# 2-1) 성적표 행렬 만들기
grade_matrix = np.array([
    [85, 90],
    [92, 88],
    [78, 95]
])

# 2-2) 좌표 행렬 만들기
coordinate_matrix = np.array([
    [1,2],
    [3,4],
    [5,1],
    [2,6]
])

# 결과 확인
print("성적표 행렬:")
print("     국어 수학")
print("철수:", grade_matrix[0])
print("영희:", grade_matrix[1])  
print("민수:", grade_matrix[2])
print(f"Shape: {grade_matrix.shape}")

print("\n좌표 행렬:")
print("      x   y")
for i in range(len(coordinate_matrix)):
    print(f"점{i+1}: {coordinate_matrix[i]}")
print(f"Shape: {coordinate_matrix.shape}")

성적표 행렬:
     국어 수학
철수: [85 90]
영희: [92 88]
민수: [78 95]
Shape: (3, 2)

좌표 행렬:
      x   y
점1: [1 2]
점2: [3 4]
점3: [5 1]
점4: [2 6]
Shape: (4, 2)


### 📝 문제 3: 특수 배열 만들기 (난이도: ⭐⭐)

In [11]:
# 문제 3 답안을 여기에 작성하세요!

# 3-1) 1부터 20까지의 짝수 배열
even_numbers = np.arange(2, 21, 2)

# 3-2) 4행 3열 0 배열
zero_matrix = np.zeros((4,3))

# 3-3) 2행 5열 1 배열  
one_matrix = np.ones((2,5))

# 3-4) 모든 원소가 7인 3x3 배열
seven_matrix = np.ones((2,5)) * 7

# 결과 확인
print("짝수 배열:", even_numbers)
print(f"\n0 배열 (shape: {zero_matrix.shape}):")
print(zero_matrix)
print(f"\n1 배열 (shape: {one_matrix.shape}):")
print(one_matrix)
print(f"\n7 배열 (shape: {seven_matrix.shape}):")
print(seven_matrix)

짝수 배열: [ 2  4  6  8 10 12 14 16 18 20]

0 배열 (shape: (4, 3)):
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

1 배열 (shape: (2, 5)):
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

7 배열 (shape: (2, 5)):
[[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]]


### 📝 문제 5: 배열 사칙연산 (난이도: ⭐⭐)

In [7]:
# 문제 5 답안을 여기에 작성하세요!

# 주어진 배열들
array_a = np.array([[10, 20], [30, 40]])
array_b = np.array([[2, 4], [6, 8]])

print("배열 A:")
print(array_a)
print("\n배열 B:")
print(array_b)

# 5-1) 기본 사칙연산
result_add = array_a + array_b
result_sub = array_a - array_b
result_mul = array_a * array_b
result_div = array_a / array_b

print("\n=== 사칙연산 결과 ===")
print("덧셈:\n", result_add)
print("뺄셈:\n", result_sub)
print("곱셈 (원소별):\n", result_mul)
print("나눗셈:\n", result_div)

# 5-2) 가격 계산
prices = np.array([1000, 1500, 2000])
discount_rate = np.array([0.1, 0.2, 0.15])
quantities = np.array([3, 2, 5])

print(f"\n=== 가격 계산 ===")
print(f"상품 가격: {prices}원")
print(f"할인율: {discount_rate} ({discount_rate*100}%)")
print(f"수량: {quantities}개")

# 할인된 총 금액 계산
total_cost = prices * (1 - discount_rate) * quantities

print(f"\n각 상품별 총 금액: {total_cost}원")
print(f"전체 총 금액: {np.sum(total_cost)}원")

배열 A:
[[10 20]
 [30 40]]

배열 B:
[[2 4]
 [6 8]]

=== 사칙연산 결과 ===
덧셈:
 [[12 24]
 [36 48]]
뺄셈:
 [[ 8 16]
 [24 32]]
곱셈 (원소별):
 [[ 20  80]
 [180 320]]
나눗셈:
 [[5. 5.]
 [5. 5.]]

=== 가격 계산 ===
상품 가격: [1000 1500 2000]원
할인율: [0.1  0.2  0.15] ([10. 20. 15.]%)
수량: [3 2 5]개

각 상품별 총 금액: [2700. 2400. 8500.]원
전체 총 금액: 13600.0원


### 📝 문제 6: 벡터 내적(곱셈의 진화!) (난이도: ⭐⭐)

In [14]:
# 문제 6 답안을 여기에 작성하세요!

# 6-1) 기본 벡터 내적
vector1 = np.array([3, 4, 5])
vector2 = np.array([[2], [6], [1]])

print("벡터 1:", vector1)
print("벡터 2:", vector2)

# 손으로 계산해보기
manual_calc = 3 * 2 + 4 * 6 + 5 * 1
print(f"\n손계산: (3×2) + (4×6) + (5×1) = {3*2} + {4*6} + {5*1} = {manual_calc}")

# NumPy로 계산
dot_result = np.dot(vector1, vector2)
print(f"NumPy 내적: {dot_result}")


print(f"모든 결과가 같나요? {manual_calc == dot_result}")

# 6-2) 영양성분 계산
calories = np.array([250, 180, 320])  # 피자, 샐러드, 햄버거
servings = np.array([2, 1, 1])        # 섭취량

print(f"\n=== 영양성분 계산 ===")
foods = ['피자', '샐러드', '햄버거']
print("음식별 칼로리와 섭취량:")
for i, food in enumerate(foods):
    print(f"{food}: {calories[i]}kcal × {servings[i]}개")

# 총 칼로리 계산 (벡터 내적 사용!)
total_calories = np.dot(calories, servings)

print(f"\n총 섭취 칼로리: {total_calories}kcal")
print(f"계산 과정: ({calories[0]}×{servings[0]}) + ({calories[1]}×{servings[1]}) + ({calories[2]}×{servings[2]}) = {total_calories}")

벡터 1: [3 4 5]
벡터 2: [[2]
 [6]
 [1]]

손계산: (3×2) + (4×6) + (5×1) = 6 + 24 + 5 = 35
NumPy 내적: [35]
모든 결과가 같나요? [ True]

=== 영양성분 계산 ===
음식별 칼로리와 섭취량:
피자: 250kcal × 2개
샐러드: 180kcal × 1개
햄버거: 320kcal × 1개

총 섭취 칼로리: 1000kcal
계산 과정: (250×2) + (180×1) + (320×1) = 1000


### 📝 문제 7: 체육대회를 준비하자! (난이도: ⭐⭐)

In [ ]:
# 문제 7 답안을 여기에 작성하세요!

# 데이터 준비
class1_heights = np.array([165, 170, 158, 172, 168, 160, 175, 163, 169, 171])
class2_heights = np.array([162, 168, 155, 178, 164, 159, 173, 166, 170, 167])

print("🏫 각 반 키 데이터")
print("1반:", class1_heights)
print("2반:", class2_heights)
print()

# 1. 각 반의 평균 키
class1_mean = np.mean(class1_heights)
class2_mean = np.mean(class2_heights)

print("📊 평균 키 비교")
print(f"1반 평균: {class1_mean:.1f}cm")
print(f"2반 평균: {class2_mean:.1f}cm")

# 2. 각 반의 키 중앙값
class1_median = np.median(class1_heights)
class2_median = np.median(class2_heights)

print(f"\n🎯 키 중앙값")
print(f"1반 중앙값: {class1_median}cm")
print(f"2반 중앙값: {class2_median}cm")

# 3. 최대/최소 키
class1_max = np.max(class1_heights)
class1_min = np.min(class1_heights)
class2_max = np.max(class2_heights)
class2_min = np.min(class2_heights)

print(f"\n📏 키 범위")
print(f"1반: {class1_min}cm ~ {class1_max}cm")
print(f"2반: {class2_min}cm ~ {class2_max}cm")

# 4. 어느 반이 더 클까?
if class1_mean > class2_mean:
    print(f"\n🏆 1반이 평균 {class1_mean - class2_mean:.1f}cm 더 큽니다!")
else:
    print(f"\n🏆 2반이 평균 {class2_mean - class1_mean:.1f}cm 더 큽니다!")

SyntaxError: invalid syntax (3346863934.py, line 13)

### 📝 문제 8: 매장 판매 데이터 분석 (난이도: ⭐⭐⭐)

In [ ]:
# 데이터 준비
sales_data = np.array([
    [150, 200, 80, 120],   # 강남점
    [180, 180, 100, 90],   # 홍대점  
    [120, 220, 60, 110]    # 신촌점
])

stores = ['강남점', '홍대점', '신촌점']
products = ['음료', '과자', '아이스크림', '도시락']

print("🏪 편의점 판매 데이터")
print("         음료  과자  아이스크림  도시락")
for i, store in enumerate(stores):
    print(f"{store}:  {sales_data[i]}")
print()

# 1. axis=0: 상품별 통계 (열별 계산)
print("📊 1. axis=0 → 상품별 통계")
print("=" * 30)
product_total = np.sum(sales_data, axis=0)      # 상품별 총 판매량
product_avg = np.mean(sales_data, axis=0)       # 상품별 평균 판매량

print(f"상품별 총 판매량: {product_total}")
print(f"상품별 평균 판매량: {product_avg}")

for i, product in enumerate(products):
    print(f"• {product}: 총 {product_total[i]}개, 평균 {product_avg[i]:.1f}개")

# 2. axis=1: 지점별 통계 (행별 계산)
print(f"\n📊 2. axis=1 → 지점별 통계")
print("=" * 30)
store_total = np.sum(sales_data, axis=1)        # 지점별 총 판매량
store_avg = np.mean(sales_data, axis=1)         # 지점별 평균 판매량

print(f"지점별 총 판매량: {store_total}")
print(f"지점별 평균 판매량: {store_avg}")

for i, store in enumerate(stores):
    print(f"• {store}: 총 {store_total[i]}개, 평균 {store_avg[i]:.1f}개")

# 3. 최고 성과 찾기
print(f"\n🏆 3. 최고 성과 분석")
print("=" * 25)
best_product_idx = np.argmax(product_total)     # 가장 잘 팔리는 상품 인덱스
best_store_idx = np.argmax(store_total)         # 가장 매출이 좋은 지점 인덱스

print(f"🥇 베스트 상품: {products[best_product_idx]} (총 {product_total[best_product_idx]}개)")
print(f"🥇 베스트 지점: {stores[best_store_idx]} (총 {store_total[best_store_idx]}개)")


🏪 편의점 판매 데이터
         음료  과자  아이스크림  도시락
강남점:  [150 200  80 120]
홍대점:  [180 180 100  90]
신촌점:  [120 220  60 110]

📊 1. axis=0 → 상품별 통계
상품별 총 판매량: [450 600 240 320]
상품별 평균 판매량: [150.         200.          80.         106.66666667]
• 음료: 총 450개, 평균 150.0개
• 과자: 총 600개, 평균 200.0개
• 아이스크림: 총 240개, 평균 80.0개
• 도시락: 총 320개, 평균 106.7개

📊 2. axis=1 → 지점별 통계
지점별 총 판매량: [550 550 510]
지점별 평균 판매량: [137.5 137.5 127.5]
• 강남점: 총 550개, 평균 137.5개
• 홍대점: 총 550개, 평균 137.5개
• 신촌점: 총 510개, 평균 127.5개

🏆 3. 최고 성과 분석
🥇 베스트 상품: 과자 (총 600개)
🥇 베스트 지점: 강남점 (총 550개)

🎯 4. 상품별 최고 판매 지점
• 음료: 홍대점 (180개)
• 과자: 신촌점 (220개)
• 아이스크림: 홍대점 (100개)
• 도시락: 강남점 (120개)

💡 비즈니스 인사이트:
• 과자가 가장 인기 상품이에요! (총 600개)
• 홍대점이 가장 매출이 좋아요! (총 550개)
• 아이스크림은 홍대점에서 가장 잘 팔려요!
• 전체 평균 판매량: 134.2개


### ✅ 문제 9 해답: 분산과 표준편차 마스터하기!

In [ ]:
# ✅ 문제 9 완전한 해답

# 데이터 준비
class_a_scores = np.array([85, 87, 83, 89, 86, 84, 88, 85, 87, 86])
class_b_scores = np.array([70, 95, 60, 100, 75, 90, 65, 85, 80, 90])

print("📊 두 반의 수학 시험 점수")
print("A반 점수:", class_a_scores)
print("B반 점수:", class_b_scores)
print()

# 1. 각 반의 평균 점수
class_a_mean = np.mean(class_a_scores)
class_b_mean = np.mean(class_b_scores)

print("📈 평균 점수 비교")
print(f"A반 평균: {class_a_mean:.1f}점")
print(f"B반 평균: {class_b_mean:.1f}점")

# 2. 각 반의 분산
class_a_var = np.sum((class_a_scores - class_a_mean)** 2 / len(class_a_scores))
class_b_var = np.sum((class_b_scores - class_b_mean)** 2 / len(class_b_scores))

print(f"\n📊 분산 비교(np.var 사용 X)")
print(f"A반 분산: {class_a_var:.2f}")
print(f"B반 분산: {class_b_var:.2f}")

class_a_var2 = np.var(class_a_scores)
class_b_var2 = np.var(class_b_scores)
print(f"\n📊 분산 비교(np.var(사용 O))")
print(f"A반 분산: {class_a_var:.2f}")
print(f"B반 분산: {class_b_var:.2f}")

# 3. 각 반의 표준편차
class_a_std = np.sqrt(class_a_var)
class_b_std = np.sqrt(class_b_var)

print(f"\n📏 표준편차 비교(np.std 사용 X)")
print(f"A반 표준편차: {class_a_std:.2f}")
print(f"B반 표준편차: {class_b_std:.2f}")

class_a_std = np.std(class_a_scores)
class_b_std = np.std(class_b_scores)

print(f"\n📏 표준편차 비교(np.std 사용)")
print(f"A반 표준편차: {class_a_std:.2f}")
print(f"B반 표준편차: {class_b_std:.2f}")
# 4. 더 일정한 점수 분포 판단

print(f"\n🎯 분석 결과")

if class_a_std < class_b_std:
    print(f"A반이 더 일정한 점수 분포를 가집니다!")
    print(f"(표준편차가 {class_b_std - class_a_std:.2f}점 더 작음)")
else:
    print(f"B반이 더 일정한 점수 분포를 가집니다!")
    print(f"(표준편차가 {class_a_std - class_b_std:.2f}점 더 작음)")

# 5. 보너스: 전체 데이터 통계
all_scores = np.concatenate([class_a_scores, class_b_scores])
print(f"\n🎉 전체 데이터 통계")
print(f"전체 평균: {np.mean(all_scores):.1f}점")
print(f"전체 분산: {np.var(all_scores):.2f}")
print(f"전체 표준편차: {np.std(all_scores):.2f}")

print(f"\n💡 해석:")
print(f"• 분산이 작을수록 → 점수가 평균 주변에 몰려있음")
print(f"• 표준편차가 작을수록 → 학생들 점수가 고르게 분포")
print(f"• 표준편차 = √분산 관계 확인: √{class_a_var:.2f} = {np.sqrt(class_a_var):.2f}")

# 추가 분석
print(f"\n🔍 상세 분석:")
print(f"• A반: 평균 {class_a_mean:.1f}, 표준편차 {class_a_std:.2f} → 안정적인 성취")
print(f"• B반: 평균 {class_b_mean:.1f}, 표준편차 {class_b_std:.2f} → 편차가 큰 성취")
print(f"• 평균은 같지만 B반이 점수 편차가 훨씬 큽니다!")

### ✅ 문제 10 해답: axis와 함께하는 분산/표준편차

In [ ]:
# ✅ 문제 10 완전한 해답

# 데이터 준비
performance_data = np.array([
    [88, 85, 90, 78],  # 1월
    [92, 82, 85, 82],  # 2월
    [85, 88, 95, 75]   # 3월
])

months = ['1월', '2월', '3월']
departments = ['개발', '디자인', '마케팅', '영업']

print("🏢 부서별 월간 성과 점수")
print("      개발  디자인  마케팅  영업")
for i, month in enumerate(months):
    print(f"{month}: {performance_data[i]}")
print()

# 1. axis=0: 부서별 분산과 표준편차 (3개월 데이터로)
print("📊 1. axis=0 → 부서별 통계 (3개월간)")
print("=" * 35)
dept_var = np.var(performance_data, axis=0)
dept_std = np.std(performance_data, axis=0)

print(f"부서별 분산:   {dept_var}")
print(f"부서별 표준편차: {dept_std}")

for i, dept in enumerate(departments):
    print(f"• {dept}: 분산 {dept_var[i]:.2f}, 표준편차 {dept_std[i]:.2f}")

# 2. axis=1: 월별 분산과 표준편차 (4개 부서 데이터로)
print(f"\n📊 2. axis=1 → 월별 통계 (4개 부서)")
print("=" * 30)
month_var = np.var(performance_data, axis=1)
month_std = np.std(performance_data, axis=1)

print(f"월별 분산:   {month_var}")
print(f"월별 표준편차: {month_std}")

for i, month in enumerate(months):
    print(f"• {month}: 분산 {month_var[i]:.2f}, 표준편차 {month_std[i]:.2f}")

# 3. 가장 일관된 부서 찾기 (표준편차가 가장 작은 부서)
print(f"\n🏆 3. 가장 일관된 성과 부서")
print("=" * 25)
most_consistent_dept_idx = np.argmin(dept_std)
min_dept_std = np.min(dept_std)

print(f"🥇 {departments[most_consistent_dept_idx]}팀이 가장 일관된 성과!")
print(f"   (표준편차: {min_dept_std:.2f})")

# 4. 가장 균등한 월 찾기 (표준편차가 가장 작은 월)
print(f"\n🌟 4. 가장 균등한 성과 월")
print("=" * 20)
most_balanced_month_idx = np.argmin(month_std)
min_month_std = np.min(month_std)

print(f"🥇 {months[most_balanced_month_idx]}이 가장 균등한 성과!")
print(f"   (표준편차: {min_month_std:.2f})")

# 5. 전체 데이터 통계
print(f"\n🎉 5. 전체 데이터 통계")
print("=" * 20)
overall_var = np.var(performance_data)
overall_std = np.std(performance_data)

print(f"전체 평균: {np.mean(performance_data):.1f}점")
print(f"전체 분산: {overall_var:.2f}")
print(f"전체 표준편차: {overall_std:.2f}")

print(f"\n💡 분석 결과:")
print(f"• 부서 중 표준편차가 가장 큰 팀: {departments[np.argmax(dept_std)]} ({np.max(dept_std):.2f})")
print(f"• 월 중 표준편차가 가장 큰 달: {months[np.argmax(month_std)]} ({np.max(month_std):.2f})")
print(f"• 전체적으로 성과가 {'일관적' if overall_std < 5 else '변동이 큰'} 회사입니다!")

### ✅ 문제 11 해답: 조건 선별 함수 마스터하기!

In [ ]:
# ✅ 문제 11 완전한 해답

# 데이터 준비
temperatures = np.array([28, 35, 32, 38, 31, 29, 40])
rainfall = np.array([0, 5, 12, 0, 3, 8, 15])
days = ['월', '화', '수', '목', '금', '토', '일']

print("🌡️ 일주일간 날씨 데이터")
print("요일:", days)
print("온도:", temperatures, "°C")
print("강수량:", rainfall, "mm")
print()

# 1. any() 사용: 35도 이상 폭염일 확인
has_heat_wave = np.any(temperatures >= 35)
print("📈 1. 폭염일(35도 이상) 존재 여부")
print(f"폭염일이 있나요? {has_heat_wave}")

# 2. all() 사용: 모든 날이 25도 이상인지 확인  
all_warm = np.all(temperatures >= 25)
print(f"\n🌞 2. 모든 날이 25도 이상인가?")
print(f"모든 날이 따뜻한가요? {all_warm}")

# 3. 비교연산자: 30도 이상인 날 표시
hot_days_mask = temperatures >= 30
print(f"\n🔥 3. 30도 이상인 날들 (True/False)")
print("온도 ≥ 30°C:", hot_days_mask)

# 실제 30도 이상인 날들 출력
hot_days = temperatures[hot_days_mask]  # 마스킹 사용
hot_day_names = [days[i] for i in range(len(days)) if hot_days_mask[i]]
print(f"30도 이상인 날: {hot_day_names}")
print(f"해당 온도: {hot_days}°C")

# 4. where() 사용: 온도에 따른 분류
weather_status = np.where(temperatures >= 35, "폭염", 
                         np.where(temperatures >= 30, "더위", "보통"))
print(f"\n🌡️ 4. 날씨 상태 분류")
for i, day in enumerate(days):
    print(f"{day}요일: {temperatures[i]}°C → {weather_status[i]}")

# 5. 복합조건: 온도 30도 이상이면서 강수량 0mm인 날
dry_hot_condition = (temperatures >= 30) & (rainfall == 0)
dry_hot_days = temperatures[dry_hot_condition]

print(f"\n☀️ 5. 건조하고 더운 날 (30도 이상 & 강수량 0mm)")
if dry_hot_condition.any():  # 조건 만족하는 날이 있다면
    dry_hot_day_names = [days[i] for i in range(len(days)) if dry_hot_condition[i]]
    print(f"해당 날짜: {dry_hot_day_names}")
    print(f"온도: {temperatures[dry_hot_condition]}°C")
else:
    print("조건을 만족하는 날이 없습니다.")

print(f"\n📊 전체 요약:")
print(f"• 평균 온도: {np.mean(temperatures):.1f}°C") 
print(f"• 총 강수량: {np.sum(rainfall)}mm")
print(f"• 폭염일 수: {np.sum(temperatures >= 35)}일")
print(f"• 강수일 수: {np.sum(rainfall > 0)}일")

### ✅ 문제 12 해답: 차원 변경(reshape) 마스터하기!

In [2]:
# ✅ 문제 12 완전한 해답

# 데이터 준비
terrain_data = np.array([1, 2, 3, 1, 4, 2, 3, 4, 1, 2, 4, 3])
terrain_names = {1: '평지🟩', 2: '산⛰️', 3: '물🌊', 4: '숲🌳'}

print("🗺️ 원본 지형 데이터 (1차원)")
print("지형 코드:", terrain_data)
print("총 원소 개수:", len(terrain_data))
print()

# 1. 3x4 직사각형 맵 (가로가 더 긴 맵)
map_3x4 = terrain_data.reshape(3, 4)
print("📐 1. 3x4 직사각형 맵 (3행 4열)")
print(map_3x4)
print(f"Shape: {map_3x4.shape}")

# 2. 4x3 직사각형 맵 (세로가 더 긴 맵)  
map_4x3 = terrain_data.reshape(4, 3)
print(f"\n📐 2. 4x3 직사각형 맵 (4행 3열)")
print(map_4x3)
print(f"Shape: {map_4x3.shape}")

# 3. 2x6 긴 맵
map_2x6 = terrain_data.reshape(2, 6)
print(f"\n📐 3. 2x6 긴 맵 (2행 6열)")
print(map_2x6)
print(f"Shape: {map_2x6.shape}")

# 4. 12x1 세로 벡터
map_12x1 = terrain_data.reshape(12, 1)
print(f"\n📐 4. 12x1 세로 벡터")
print(map_12x1)
print(f"Shape: {map_12x1.shape}")

# 5. 창의문제: 6x2 맵과 지형 타입 개수 세기
map_6x2 = terrain_data.reshape(6, 2)
print(f"\n🎯 5. 6x2 맵 (6행 2열)")
print(map_6x2)
print(f"Shape: {map_6x2.shape}")

🗺️ 원본 지형 데이터 (1차원)
지형 코드: [1 2 3 1 4 2 3 4 1 2 4 3]
총 원소 개수: 12

📐 1. 3x4 직사각형 맵 (3행 4열)
[[1 2 3 1]
 [4 2 3 4]
 [1 2 4 3]]
Shape: (3, 4)

📐 2. 4x3 직사각형 맵 (4행 3열)
[[1 2 3]
 [1 4 2]
 [3 4 1]
 [2 4 3]]
Shape: (4, 3)

📐 3. 2x6 긴 맵 (2행 6열)
[[1 2 3 1 4 2]
 [3 4 1 2 4 3]]
Shape: (2, 6)

📐 4. 12x1 세로 벡터
[[1]
 [2]
 [3]
 [1]
 [4]
 [2]
 [3]
 [4]
 [1]
 [2]
 [4]
 [3]]
Shape: (12, 1)

🎯 5. 6x2 맵 (6행 2열)
[[1 2]
 [3 1]
 [4 2]
 [3 4]
 [1 2]
 [4 3]]
Shape: (6, 2)


### ✅ 문제 13 해답: 브로드캐스팅의 마법!

In [ ]:
# ✅ 문제 13 완전한 해답

# 데이터 준비
base_prices = np.array([
#   음료,   과자,  도시락, 아이스크림
    [1000, 1500, 2000, 800],   # 강남점
    [950, 1400, 1900, 750],    # 홍대점  
    [1100, 1600, 2100, 850]    # 신촌점
])

product_discounts = np.array([0.1, 0.15, 0.05, 0.2])  # 상품별 할인율
store_discounts = np.array([[0.05], [0.1], [0.03]])   # 지점별 할인율

stores = ['강남점', '홍대점', '신촌점']
products = ['음료', '과자', '도시락', '아이스크림']

print("🏪 편의점 기본 가격표")
print("        음료   과자  도시락  아이스크림")
for i, store in enumerate(stores):
    print(f"{store}: {base_prices[i]}원")
print()

print("💰 할인 정보")
print("상품별 할인율:", product_discounts * 100, "%")
print("지점별 할인율:", store_discounts.flatten() * 100, "%")
print()

# 1. 스칼라 브로드캐스팅: VAT 10% 추가
vat_prices = base_prices * 1.1  # 모든 원소에 1.1 곱하기
print("📈 1. VAT 10% 적용 후 가격")
print("        음료   과자  도시락  아이스크림")
for i, store in enumerate(stores):
    print(f"{store}: {vat_prices[i].astype(int)}원")
print()

# 2. 1차원 브로드캐스팅: 상품별 할인 적용
product_discounted_prices = base_prices * (1 - product_discounts)
print("🎯 2. 상품별 할인 적용 후 가격")
print("        음료   과자  도시락  아이스크림")
for i, store in enumerate(stores):
    print(f"{store}: {product_discounted_prices[i].astype(int)}원")
print()

# 3. 2차원 브로드캐스팅: 지점별 추가 할인 적용  
store_discounted_prices = base_prices * (1 - store_discounts)
print("🏢 3. 지점별 할인 적용 후 가격")
print("        음료   과자  도시락  아이스크림") 
for i, store in enumerate(stores):
    print(f"{store}: {store_discounted_prices[i].astype(int)}원")
print()

# 4. 복합 브로드캐스팅: 상품별 + 지점별 할인 동시 적용
final_prices = base_prices * (1 - product_discounts) * (1 - store_discounts)
print("🎉 4. 최종 할인 가격 (상품할인 + 지점할인)")
print("        음료   과자  도시락  아이스크림")
for i, store in enumerate(stores):
    print(f"{store}: {final_prices[i].astype(int)}원")
print()