In [2]:
import numpy as np

## 통계 함수
- 배열 내 원소의 합계, 평균, 중앙값, 최댓값, 최솟값, 분산, 표준편차 등을 구할 때 통계함수인 sum(), mean(), median(), max(), min(), var(), std()를 사용한다.

### sum() 함수
- sum() 함수를 사용하여 배열에서 모든 원소를 더하거나 행 또는 열을 기준으로 합계를 구할 수 있다.

In [3]:
owl6 = np.array([[1,2,3], [4,5,6]])
owl6

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# 배열 내 모든 원소를 다 더할 때
np.sum(owl6)

np.int64(21)

In [5]:
# 열의 원소 합계
np.sum(owl6, axis = 0)

array([5, 7, 9])

In [6]:
# 행의 원소 합계
np.sum(owl6, axis = 1)

array([ 6, 15])

### mean() 함수
- mean() 함수를 사용하여 배열에서 모든 원소 또는 행이나 열을 기준으로 값들의 평균을 구할 수 있다.

In [7]:
# 모든 원소의 평균을 구할 때
np.mean(owl6)

np.float64(3.5)

In [8]:
# 열별 원소 평균을 구할 때
np.mean(owl6, axis = 0)

array([2.5, 3.5, 4.5])

In [9]:
# 행별 원소 평균을 구할 때
np.mean(owl6, axis = 1)

array([2., 5.])

### median() 함수
- 중앙값이란 원소를 작은 값에서 큰 값 순서로 나열했을 때 중앙에 위치하는 값
- median() 함수를 사용하여 배열에서 모든 원소 또는 행이나 열을 기준으로 값들의 중앙값을 구할 수 있다.

In [11]:
owl8 = np.array([[1,4,3,7,8], [2,1,5,3,6], [3,3,4,1,5]])
owl8

array([[1, 4, 3, 7, 8],
       [2, 1, 5, 3, 6],
       [3, 3, 4, 1, 5]])

In [12]:
# 모든 원소의 중앙값
np.median(owl8)

np.float64(3.0)

In [13]:
# 열끼리 원소 중앙값
np.median(owl8, axis = 0)

array([2., 3., 4., 3., 6.])

In [14]:
# 행끼리 원소 중앙값
np.median(owl8, axis = 1)

array([4., 3., 3.])

### max() 함수와 min() 함수
- 배열의 원소 중 최댓값과 최솟값을 구할 때는 max() 함수와 min() 함수를 사용한다.

In [15]:
# 배열 내 모든 원소들 중 최대값
np.max(owl8)

np.int64(8)

In [16]:
# 배열 내 모든 원소들 중 최소값
np.min(owl8)

np.int64(1)

In [17]:
# 열끼리 원소의 최대값
np.max(owl8, axis = 0)

array([3, 4, 5, 7, 8])

In [18]:
# 열끼리 원소의 최솟값
np.min(owl8, axis = 0)

array([1, 1, 3, 1, 5])

In [19]:
# 행끼리 원소의 최대값
np.max(owl8, axis = 1)

array([8, 6, 5])

In [20]:
# 행끼리 원소의 최솟값
np.min(owl8, axis = 1)

array([1, 1, 1])

### argmax() 함수와 argmin() 함수
- 최댓값과 최솟값에 해당하는 인덱스를 출력하려면 argmax() 함수와 argmin() 함수를 사용한다.

In [21]:
# 최댓값의 위치(인덱스) 출력
np.argmax(owl8)

np.int64(4)

In [22]:
# 최솟값의 위치(인덱스) 출력
np.argmin(owl8)

np.int64(0)

### 분산과 표준편차

#### 분산 
- 원소들이 평균에서 얼마나 흩어져 있는지를 분포로 나타냄(ppt 참조)
- 분산값이 커질수록 평균에서 많이 흩어져 있다는 걸 알 수 있음 
- var() 함수 사용 

#### 표준편차
- 원소들이 평균에서 얼마나 떨어져 있는지를 나타내는 수치(ppt 참조)
- 표준편차값이 작을수록 평균값에서 원소들의 거리가 가깝다는 걸 알 수 있음
- std() 함수 사용

In [24]:
# 전체 원소들의 분산값
np.var(owl8)

np.float64(4.328888888888889)

In [25]:
# 전체 원소들의 표준편차값
np.std(owl8)

np.float64(2.0805982045769644)

In [26]:
# 열끼리 원소의 분산
np.var(owl8, axis = 0)

array([0.66666667, 1.55555556, 0.66666667, 6.22222222, 1.55555556])

In [27]:
# 열끼리 원소의 표준편차
np.std(owl8, axis = 0)

array([0.81649658, 1.24721913, 0.81649658, 2.49443826, 1.24721913])

In [28]:
# 행끼리 원소의 분산
np.var(owl8, axis = 1)

array([6.64, 3.44, 1.76])

In [ ]:
# 행끼리 원소의 표준편차
np.std(owl8, axis = 1 )

### 예시)부엉이 가족들 나이의 분산과 표준편차 

In [ ]:
# 아들 : 4살, 딸 : 12살, 엄마 : 41살, 할아버지 : 60, 할머니 : 70
owl_age = np.array([4,12,41,60,70])

In [ ]:
# 부엉이 가족들의 나이 평균 구하기
age_mean = np.mean(owl_age)

In [ ]:
# 부엉이 가족들의 나이 분산 구하기
owl_var = np.sum((owl_age - age_mean)** 2 / 5)
owl_var

np.float64(669.44)

In [ ]:
# var() 함수를 통해 구하기
np.var(owl_age)

np.float64(669.4399999999999)

In [ ]:
# 표준편차 구하기
owl_std = np.sqrt(owl_var)
owl_std

np.float64(25.873538606073968)

In [ ]:
# std() 함수를 통해 구하기
np.std(owl_age)

np.float64(25.873538606073964)

## 조건에 따른 선별 함수
- 넘파이 배열 내 원소들 중 특정 조건을 만족하는 원소를 찾을 때 any(), all(), where() 함수를 사용한다.

### any() 함수
- any() 함수는 배열에서 특정 조건을 만족하는 원소가 1개라도 있을 때 'True'를 출력하고 없다면 'False'를 출력한다.

In [39]:
owl9 = np.array([[1.9, -0.6, -0.7, 0.55, -0.9], [0.1, 0.56, -0.78, 0.27, 0.6],
                 [ -0.14, 0.04, -0.6, -1.4, 0.9]])
owl9

array([[ 1.9 , -0.6 , -0.7 ,  0.55, -0.9 ],
       [ 0.1 ,  0.56, -0.78,  0.27,  0.6 ],
       [-0.14,  0.04, -0.6 , -1.4 ,  0.9 ]])

In [ ]:
# any() 함수 사용
np.any(owl9>0)

np.True_

### all() 함수
- all() 함수는 배열에서 특정 조건을 모든 원소가 만족할 때 'True'를 출력하고 그렇지 않으면 'False'를 출력한다.

In [41]:
# all() 함수 사용
np.all(owl9 > 0)

np.False_

### where 함수
- 배열 내 원소들 중 특정 조건을 만족하는 것과 그렇지 않은 것에 대한 서로 다른 결과를 출력할 떄 사용한다.
- 파이썬의 if ~ else절과 비슷하다.

In [42]:
# 조건(owl9 > 0)가 참일 때는 owl9(그대로), 거짓일 때는 0으로 설정
np.where(owl9 > 0, owl9, 0)

array([[1.9 , 0.  , 0.  , 0.55, 0.  ],
       [0.1 , 0.56, 0.  , 0.27, 0.6 ],
       [0.  , 0.04, 0.  , 0.  , 0.9 ]])

### 원소별로 하나씩 비교할 떄는?

In [44]:
# 비교 연산자를 활용하여 원소별로 하나씩 비교할 수 있다.
owl9 > 0

array([[ True, False, False,  True, False],
       [ True,  True, False,  True,  True],
       [False,  True, False, False,  True]])

## 차원 번경
- reshape() 함수를 사용하여 배열의 모양을 번경할 수 있다.

In [45]:
owl10 = np.array([1,2,3])
owl10

array([1, 2, 3])

In [ ]:
# reshape() 함수 사용
owl10.reshape(3,1)

array([[1],
       [2],
       [3]])

## 브로드캐스팅
- 일정 조건만 맞으면 서로 다른 모양의 배열끼리 연산할 수 있도록 하는 기능이다.
- 다음 조건 중 하나를 만족하면 브로드캐스팅이 가능하다.
    - 한 배열의 차원이 1일 때
    - 첫번째 배열의 행의 개수와 두번째 배열의 열의 개수가 같을 때

In [47]:
### 유형 1
owl10 + 1

array([2, 3, 4])

In [ ]:
### 유형 2 - 앞 배열의 행갯수가 3, 뒷 배열의 열갯수도 3
np.arange(9).reshape(3,3) + np.arange(3)

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [ ]:
### 유형3 - 앞 배열의 행갯수가 3, 뒷 배열의 열갯수도 3
owl10.reshape(3,1) + np.arange(3)

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])