In [2]:
import numpy as np

## Numpy 문제

### 📝 문제 1: 기본 벡터 만들기 (난이도: ⭐)

다음 조건에 맞는 배열을 만들어보세요:

**1-1) 행 벡터 만들기**
- 숫자 10, 20, 30이 들어있는 행 벡터를 만드세요
- 변수명: `my_row_vector`

**1-2) 열 벡터 만들기**  
- 숫자 5, 15, 25가 들어있는 열 벡터를 만드세요
- 변수명: `my_col_vector`

**힌트:** 행 벡터는 `[[]]`, 열 벡터는 `[[숫자], [숫자], [숫자]]` 형태예요!

In [3]:
# 문제 1 답안을 여기에 작성하세요!

# 1-1) 행 벡터 만들기
my_row_vector = np.array([10,20,30])

# 1-2) 열 벡터 만들기  
my_col_vector = np.array([[5], [15], [25]])

# 결과 확인
print("행 벡터:")
display(my_row_vector)
print("열 벡터:")
display(my_col_vector)

행 벡터:


array([10, 20, 30])

열 벡터:


array([[ 5],
       [15],
       [25]])

### 📝 문제 2: 행렬 만들기 (난이도: ⭐⭐)

**2-1) 성적표 행렬 만들기**
- 3명의 학생, 2과목(국어, 수학) 성적을 나타내는 행렬을 만드세요
- 철수: 국어 85점, 수학 90점
- 영희: 국어 92점, 수학 88점  
- 민수: 국어 78점, 수학 95점
- 변수명: `grade_matrix`

**2-2) 좌표 행렬 만들기**
- 4개 점의 (x, y) 좌표를 나타내는 행렬을 만드세요
- 점1: (1, 2), 점2: (3, 4), 점3: (5, 1), 점4: (2, 6)
- 변수명: `coordinate_matrix`

**생각해보기:** 각 행렬의 shape는 어떻게 될까요?

In [4]:
# 문제 2 답안을 여기에 작성하세요!

# 2-1) 성적표 행렬 만들기
grade_matrix = np.array([
    [85, 90],
    [92, 88],
    [78, 95]
])

# 2-2) 좌표 행렬 만들기
coordinate_matrix = np.array([
    [1,2],
    [3,4],
    [5,1],
    [2,6]
])

# 결과 확인
print("성적표 행렬:")
print("     국어 수학")
print("철수:", grade_matrix[0])
print("영희:", grade_matrix[1])  
print("민수:", grade_matrix[2])
print(f"Shape: {grade_matrix.shape}")

print("\n좌표 행렬:")
print("      x   y")
for i in range(len(coordinate_matrix)):
    print(f"점{i+1}: {coordinate_matrix[i]}")
print(f"Shape: {coordinate_matrix.shape}")

성적표 행렬:
     국어 수학
철수: [85 90]
영희: [92 88]
민수: [78 95]
Shape: (3, 2)

좌표 행렬:
      x   y
점1: [1 2]
점2: [3 4]
점3: [5 1]
점4: [2 6]
Shape: (4, 2)


### 📝 문제 3: 특수 배열 만들기 (난이도: ⭐⭐)

편리한 함수들을 사용해서 배열을 만들어보세요!

**3-1) arange() 함수 활용**
- 1부터 20까지의 짝수만 들어있는 배열을 만드세요
- 변수명: `even_numbers`

**3-2) zeros() 함수 활용**  
- 4행 3열 크기의 0으로 가득 찬 배열을 만드세요
- 변수명: `zero_matrix`

**3-3) ones() 함수 활용**
- 2행 5열 크기의 1로 가득 찬 배열을 만드세요  
- 변수명: `one_matrix`

**3-4) 창의 문제**
- `ones()` 함수로 만든 배열에 숫자를 곱해서 모든 원소가 7인 3x3 배열을 만드세요
- 변수명: `seven_matrix`

In [11]:
# 문제 3 답안을 여기에 작성하세요!

# 3-1) 1부터 20까지의 짝수 배열
even_numbers = np.arange(2, 21, 2)

# 3-2) 4행 3열 0 배열
zero_matrix = np.zeros((4,3))

# 3-3) 2행 5열 1 배열  
one_matrix = np.ones((2,5))

# 3-4) 모든 원소가 7인 3x3 배열
seven_matrix = np.ones((2,5)) * 7

# 결과 확인
print("짝수 배열:", even_numbers)
print(f"\n0 배열 (shape: {zero_matrix.shape}):")
print(zero_matrix)
print(f"\n1 배열 (shape: {one_matrix.shape}):")
print(one_matrix)
print(f"\n7 배열 (shape: {seven_matrix.shape}):")
print(seven_matrix)

짝수 배열: [ 2  4  6  8 10 12 14 16 18 20]

0 배열 (shape: (4, 3)):
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

1 배열 (shape: (2, 5)):
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

7 배열 (shape: (2, 5)):
[[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]]


### 📝 문제 5: 배열 사칙연산 (난이도: ⭐⭐)

**5-1) 기본 사칙연산 연습**
다음 두 배열로 사칙연산을 수행해보세요:
```python
array_a = np.array([[10, 20], [30, 40]])
array_b = np.array([[2, 4], [6, 8]])
```

- 덧셈 결과를 `result_add`에 저장
- 뺄셈 결과를 `result_sub`에 저장  
- 곱셈 결과를 `result_mul`에 저장 (⚠️ 원소별 곱셈)
- 나눗셈 결과를 `result_div`에 저장

**5-2) 실생활 응용: 가격 계산**
- 상품 가격: `prices = np.array([1000, 1500, 2000])` (원)
- 할인율: `discount_rate = np.array([0.1, 0.2, 0.15])` (10%, 20%, 15%)
- 수량: `quantities = np.array([3, 2, 5])` (개)

할인된 총 금액을 계산하세요! (가격 × (1-할인율) × 수량)
결과를 `total_cost`에 저장하세요.

In [7]:
# 문제 5 답안을 여기에 작성하세요!

# 주어진 배열들
array_a = np.array([[10, 20], [30, 40]])
array_b = np.array([[2, 4], [6, 8]])

print("배열 A:")
print(array_a)
print("\n배열 B:")
print(array_b)

# 5-1) 기본 사칙연산
result_add = array_a + array_b
result_sub = array_a - array_b
result_mul = array_a * array_b
result_div = array_a / array_b

print("\n=== 사칙연산 결과 ===")
print("덧셈:\n", result_add)
print("뺄셈:\n", result_sub)
print("곱셈 (원소별):\n", result_mul)
print("나눗셈:\n", result_div)

# 5-2) 가격 계산
prices = np.array([1000, 1500, 2000])
discount_rate = np.array([0.1, 0.2, 0.15])
quantities = np.array([3, 2, 5])

print(f"\n=== 가격 계산 ===")
print(f"상품 가격: {prices}원")
print(f"할인율: {discount_rate} ({discount_rate*100}%)")
print(f"수량: {quantities}개")

# 할인된 총 금액 계산
total_cost = prices * (1 - discount_rate) * quantities

print(f"\n각 상품별 총 금액: {total_cost}원")
print(f"전체 총 금액: {np.sum(total_cost)}원")

배열 A:
[[10 20]
 [30 40]]

배열 B:
[[2 4]
 [6 8]]

=== 사칙연산 결과 ===
덧셈:
 [[12 24]
 [36 48]]
뺄셈:
 [[ 8 16]
 [24 32]]
곱셈 (원소별):
 [[ 20  80]
 [180 320]]
나눗셈:
 [[5. 5.]
 [5. 5.]]

=== 가격 계산 ===
상품 가격: [1000 1500 2000]원
할인율: [0.1  0.2  0.15] ([10. 20. 15.]%)
수량: [3 2 5]개

각 상품별 총 금액: [2700. 2400. 8500.]원
전체 총 금액: 13600.0원


### 📝 문제 6: 벡터 내적(곱셈의 진화!) (난이도: ⭐⭐)


```
            [d,
[a, b, c] ×  e,
             f] = (a×d) + (b×e) + (c×f)
```

**6-1) 기본 벡터 내적**
다음 두 벡터의 내적을 계산하세요:
```python
vector1 = np.array([3, 4, 5])
vector2 = np.array([[2], [6], [1]])
```
- 손으로 계산한 결과와 `np.dot()` 결과를 비교해보세요!
- 결과를 `dot_result`에 저장

**6-2) 실생활 응용: 영양성분 계산**
- 음식별 칼로리: `calories = np.array([250, 180, 320])` (피자, 샐러드, 햄버거)
- 섭취량(개): `servings = np.array([2, 1, 1])` 

총 칼로리를 벡터 내적으로 계산하세요!
결과를 `total_calories`에 저장하세요.

In [14]:
# 문제 6 답안을 여기에 작성하세요!

# 6-1) 기본 벡터 내적
vector1 = np.array([3, 4, 5])
vector2 = np.array([[2], [6], [1]])

print("벡터 1:", vector1)
print("벡터 2:", vector2)

# 손으로 계산해보기
manual_calc = 3 * 2 + 4 * 6 + 5 * 1
print(f"\n손계산: (3×2) + (4×6) + (5×1) = {3*2} + {4*6} + {5*1} = {manual_calc}")

# NumPy로 계산
dot_result = np.dot(vector1, vector2)
print(f"NumPy 내적: {dot_result}")


print(f"모든 결과가 같나요? {manual_calc == dot_result}")

# 6-2) 영양성분 계산
calories = np.array([250, 180, 320])  # 피자, 샐러드, 햄버거
servings = np.array([2, 1, 1])        # 섭취량

print(f"\n=== 영양성분 계산 ===")
foods = ['피자', '샐러드', '햄버거']
print("음식별 칼로리와 섭취량:")
for i, food in enumerate(foods):
    print(f"{food}: {calories[i]}kcal × {servings[i]}개")

# 총 칼로리 계산 (벡터 내적 사용!)
total_calories = np.dot(calories, servings)

print(f"\n총 섭취 칼로리: {total_calories}kcal")
print(f"계산 과정: ({calories[0]}×{servings[0]}) + ({calories[1]}×{servings[1]}) + ({calories[2]}×{servings[2]}) = {total_calories}")

벡터 1: [3 4 5]
벡터 2: [[2]
 [6]
 [1]]

손계산: (3×2) + (4×6) + (5×1) = 6 + 24 + 5 = 35
NumPy 내적: [35]
모든 결과가 같나요? [ True]

=== 영양성분 계산 ===
음식별 칼로리와 섭취량:
피자: 250kcal × 2개
샐러드: 180kcal × 1개
햄버거: 320kcal × 1개

총 섭취 칼로리: 1000kcal
계산 과정: (250×2) + (180×1) + (320×1) = 1000


### 📝 문제 7: 체육대회를 준비하자! (난이도: ⭐⭐)

**🎯 상황:** 
당신은 학급 임원으로 체육대회 준비를 하고 있습니다. 
각 반의 키 데이터를 분석해서 줄넘기 대표팀을 선발해야 해요!

**📊 데이터:**
```python
# 1반 학생들의 키 (cm)
class1_heights = np.array([165, 170, 158, 172, 168, 160, 175, 163, 169, 171])

# 2반 학생들의 키 (cm)  
class2_heights = np.array([162, 168, 155, 178, 164, 159, 173, 166, 170, 167])
```

**🚀 미션:**
1. 각 반의 평균 키를 구하세요
2. 각 반의 키 중앙값을 구하세요
3. 각 반에서 가장 큰 키와 작은 키를 찾으세요
4. 어느 반이 더 키가 클까요? (평균 비교)
5. **보너스**: 두 반을 합쳤을 때의 전체 통계를 구해보세요!

In [ ]:
# 문제 7 답안을 여기에 작성하세요!

# 데이터 준비
class1_heights = np.array([165, 170, 158, 172, 168, 160, 175, 163, 169, 171])
class2_heights = np.array([162, 168, 155, 178, 164, 159, 173, 166, 170, 167])

print("🏫 각 반 키 데이터")
print("1반:", class1_heights)
print("2반:", class2_heights)
print()

# 1. 각 반의 평균 키
class1_mean = np.mean(class1_heights)
class2_mean = np.mean(class2_heights)

print("📊 평균 키 비교")
print(f"1반 평균: {class1_mean:.1f}cm")
print(f"2반 평균: {class2_mean:.1f}cm")

# 2. 각 반의 키 중앙값
class1_median = np.median(class1_heights)
class2_median = np.median(class2_heights)

print(f"\n🎯 키 중앙값")
print(f"1반 중앙값: {class1_median}cm")
print(f"2반 중앙값: {class2_median}cm")

# 3. 최대/최소 키
class1_max = np.max(class1_heights)
class1_min = np.min(class1_heights)
class2_max = np.max(class2_heights)
class2_min = np.min(class2_heights)

print(f"\n📏 키 범위")
print(f"1반: {class1_min}cm ~ {class1_max}cm")
print(f"2반: {class2_min}cm ~ {class2_max}cm")

# 4. 어느 반이 더 클까?
if class1_mean > class2_mean:
    print(f"\n🏆 1반이 평균 {class1_mean - class2_mean:.1f}cm 더 큽니다!")
else:
    print(f"\n🏆 2반이 평균 {class2_mean - class1_mean:.1f}cm 더 큽니다!")

SyntaxError: invalid syntax (3346863934.py, line 13)

### 📝 문제 8: 매장 판매 데이터 분석 (난이도: ⭐⭐⭐)

**🏪 상황:**
당신은 편의점 사장입니다. 3개 지점의 4가지 상품 판매량을 분석해야 해요!

**📊 데이터:**
```python
# 판매량 데이터 (개수)
# 행: 지점(강남점, 홍대점, 신촌점)
# 열: 상품(음료, 과자, 아이스크림, 도시락)
sales_data = np.array([
    [150, 200, 80, 120],   # 강남점
    [180, 180, 100, 90],   # 홍대점  
    [120, 220, 60, 110]    # 신촌점
])
```

**🚀 미션:**
1. **axis=0 사용**: 상품별 총 판매량과 평균 판매량을 구하세요
2. **axis=1 사용**: 지점별 총 판매량과 평균 판매량을 구하세요
3. 가장 잘 팔리는 상품과 가장 매출이 좋은 지점을 찾으세요
4. 각 상품별로 가장 잘 팔리는 지점을 찾으세요

In [8]:
# 데이터 준비
sales_data = np.array([
    [150, 200, 80, 120],   # 강남점
    [180, 180, 100, 90],   # 홍대점  
    [120, 220, 60, 110]    # 신촌점
])

stores = ['강남점', '홍대점', '신촌점']
products = ['음료', '과자', '아이스크림', '도시락']

print("🏪 편의점 판매 데이터")
print("         음료  과자  아이스크림  도시락")
for i, store in enumerate(stores):
    print(f"{store}:  {sales_data[i]}")
print()

# 1. axis=0: 상품별 통계 (열별 계산)
print("📊 1. axis=0 → 상품별 통계")
print("=" * 30)
product_total = np.sum(sales_data, axis=0)      # 상품별 총 판매량
product_avg = np.mean(sales_data, axis=0)       # 상품별 평균 판매량

print(f"상품별 총 판매량: {product_total}")
print(f"상품별 평균 판매량: {product_avg}")

for i, product in enumerate(products):
    print(f"• {product}: 총 {product_total[i]}개, 평균 {product_avg[i]:.1f}개")

# 2. axis=1: 지점별 통계 (행별 계산)
print(f"\n📊 2. axis=1 → 지점별 통계")
print("=" * 30)
store_total = np.sum(sales_data, axis=1)        # 지점별 총 판매량
store_avg = np.mean(sales_data, axis=1)         # 지점별 평균 판매량

print(f"지점별 총 판매량: {store_total}")
print(f"지점별 평균 판매량: {store_avg}")

for i, store in enumerate(stores):
    print(f"• {store}: 총 {store_total[i]}개, 평균 {store_avg[i]:.1f}개")

# 3. 최고 성과 찾기
print(f"\n🏆 3. 최고 성과 분석")
print("=" * 25)
best_product_idx = np.argmax(product_total)     # 가장 잘 팔리는 상품 인덱스
best_store_idx = np.argmax(store_total)         # 가장 매출이 좋은 지점 인덱스

print(f"🥇 베스트 상품: {products[best_product_idx]} (총 {product_total[best_product_idx]}개)")
print(f"🥇 베스트 지점: {stores[best_store_idx]} (총 {store_total[best_store_idx]}개)")

# 4. 상품별 최고 지점
print(f"\n🎯 4. 상품별 최고 판매 지점")
print("=" * 30)
best_stores_per_product = np.argmax(sales_data, axis=0)  # 각 상품별 최고 지점
max_sales_per_product = np.max(sales_data, axis=0)       # 각 상품별 최고 판매량

for i, product in enumerate(products):
    best_store_idx = best_stores_per_product[i]
    max_sales = max_sales_per_product[i]
    print(f"• {product}: {stores[best_store_idx]} ({max_sales}개)")

print(f"\n💡 비즈니스 인사이트:")
print(f"• 과자가 가장 인기 상품이에요! (총 {product_total[1]}개)")
print(f"• 홍대점이 가장 매출이 좋아요! (총 {store_total[1]}개)")
print(f"• 아이스크림은 홍대점에서 가장 잘 팔려요!")
print(f"• 전체 평균 판매량: {np.mean(sales_data):.1f}개")

🏪 편의점 판매 데이터
         음료  과자  아이스크림  도시락
강남점:  [150 200  80 120]
홍대점:  [180 180 100  90]
신촌점:  [120 220  60 110]

📊 1. axis=0 → 상품별 통계
상품별 총 판매량: [450 600 240 320]
상품별 평균 판매량: [150.         200.          80.         106.66666667]
• 음료: 총 450개, 평균 150.0개
• 과자: 총 600개, 평균 200.0개
• 아이스크림: 총 240개, 평균 80.0개
• 도시락: 총 320개, 평균 106.7개

📊 2. axis=1 → 지점별 통계
지점별 총 판매량: [550 550 510]
지점별 평균 판매량: [137.5 137.5 127.5]
• 강남점: 총 550개, 평균 137.5개
• 홍대점: 총 550개, 평균 137.5개
• 신촌점: 총 510개, 평균 127.5개

🏆 3. 최고 성과 분석
🥇 베스트 상품: 과자 (총 600개)
🥇 베스트 지점: 강남점 (총 550개)

🎯 4. 상품별 최고 판매 지점
• 음료: 홍대점 (180개)
• 과자: 신촌점 (220개)
• 아이스크림: 홍대점 (100개)
• 도시락: 강남점 (120개)

💡 비즈니스 인사이트:
• 과자가 가장 인기 상품이에요! (총 600개)
• 홍대점이 가장 매출이 좋아요! (총 550개)
• 아이스크림은 홍대점에서 가장 잘 팔려요!
• 전체 평균 판매량: 134.2개
